### PR TITLE
Wallet core@gideon

### PR DESCRIPTION
**Pull request by Ghidyon**
**PR Description:**
Created Reusuable components [`Button`, `ToggleSwitch`]  in `components` folder

**PR type:**
`feature`

**Card URL**
https://trello.com/c/sm60jM86

### CODE REVIEW

**Comment by kingsley-einstein** [comment]
@Ghidyon Please import the default member of `styled-components/native` instead. The default member you imported is meant to work only on the web. Once this is done, change `styled.button` to `styled.Button`. Also check out @theafolayan 's comment on my latest PR.

**Review by kingsley-einstein — CHANGES_REQUESTED** [review]
Please check the comments on this PR and implement the changes.

**Comment by Ghidyon** [comment]
> Please check the comments on this PR and implement the changes.

Changes implemented!

**Review by kingsley-einstein — APPROVED** [review]
Looks good to me!

**Pull request merged**
