### PR TITLE
feature: Add TouchableOpacity as reusable component

### PR DESCRIPTION
**Pull request by kingsley-einstein**
**PR description:**
Reusable component [TouchableOpacity] created in components folder.

**PR type:**
feature

**Card URL:**
[https://trello.com/c/NilpUNXZ](https://trello.com/c/NilpUNXZ)

### CODE REVIEW

**Comment by theafolayan** [comment]
Uhm @kingsley-einstein  doesn't it make sense to have default values for the specified props?

**Comment by kingsley-einstein** [comment]
> Uhm @kingsley-einstein doesn't it make sense to have default values for the specified props?

I'll make the update

**Comment by theafolayan** [comment]
> > Uhm @kingsley-einstein doesn't it make sense to have default values for the specified props?
> 
> I'll make the update

@Ghidyon Can you take note of this in your button PR too?

**Comment by kingsley-einstein** [comment]
@theafolayan I have made the updates. Please review and let me know if it is satisfactory.

**Review by theafolayan — APPROVED** [review]
Looks good to me!

**Comment by theafolayan** [comment]
Hey @kingsley-einstein Somehow missed this earlier, but shouldn't the component have a transparent background by default?
For instance when adding textual links, just so it inherits the background of it's the child?

**Comment by kingsley-einstein** [comment]
@theafolayan I'll set a default transparent background right away.

**Comment by Ghidyon** [comment]
> > > Uhm @kingsley-einstein doesn't it make sense to have default values for the specified props?
> > 
> > 
> > I'll make the update
> 
> @Ghidyon Can you take note of this in your button PR too?

Noted, I'll make changes.

**Pull request merged**
